# Task 3 Prediction using Decision Tree Algorithm
### For the given ‘Iris’ dataset, create the Decision Tree classifier and visualize it graphically. 
## By [Lakshya Bansal](http://www.lakshyabansal.me/)

**Installing Dependencies**

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

**Loading Dataset**

In [18]:
iris_data=datasets.load_iris()
X=iris_data.data
Y=iris_data.target

**Splitting Dataset**

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)

**Initializing and training model**

In [20]:
dtc=DecisionTreeClassifier(random_state=1)
dtc_model=dtc.fit(X_train,Y_train)

**Plotting Tree**

In [21]:
_ = tree.plot_tree(dtc,feature_names=iris_data.feature_names,class_names=iris_data.target_names,filled=True)

**Text Representation**

In [22]:
text_representation = tree.export_text(dtc)
print(text_representation)

|--- feature_3 <= 0.80
|   |--- class: 0
|--- feature_3 >  0.80
|   |--- feature_3 <= 1.75
|   |   |--- feature_2 <= 4.95
|   |   |   |--- feature_3 <= 1.65
|   |   |   |   |--- class: 1
|   |   |   |--- feature_3 >  1.65
|   |   |   |   |--- class: 2
|   |   |--- feature_2 >  4.95
|   |   |   |--- feature_3 <= 1.55
|   |   |   |   |--- class: 2
|   |   |   |--- feature_3 >  1.55
|   |   |   |   |--- class: 1
|   |--- feature_3 >  1.75
|   |   |--- feature_2 <= 4.85
|   |   |   |--- feature_0 <= 5.95
|   |   |   |   |--- class: 1
|   |   |   |--- feature_0 >  5.95
|   |   |   |   |--- class: 2
|   |   |--- feature_2 >  4.85
|   |   |   |--- class: 2



**Predicting Model**

In [29]:
Y_pred=dtc_model.predict(X_test)

**Evaluating Model**

In [30]:
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[ 7  0  0]
 [ 0  8  0]
 [ 0  1 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.89      1.00      0.94         8
           2       1.00      0.93      0.97        15

    accuracy                           0.97        30
   macro avg       0.96      0.98      0.97        30
weighted avg       0.97      0.97      0.97        30

